config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("cyberexperiment.core.urls", namespace="core")),
    path("lab/", include("cyberexperiment.lab.urls", namespace="lab")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("cyberexperiment.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

cyberexperiment/core/urls.py
from django.urls import path

from .views import (
    AboutView,
    BlogDetailView,
    BlogView,
    ContactView,
    Dashboard,
    EventView,
    Explore,
    FollowerView,
    HomePageView,
    InstructorView,
)

app_name = "core"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("blog/", BlogView.as_view(), name="blog"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("blog-detail", BlogDetailView.as_view(), name="blog-details"),
    path("event/", EventView.as_view(), name="event"),
    path("follower/", FollowerView.as_view(), name="follower"),
    path("instructor/", InstructorView.as_view(), name="instructor"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("explore/", Explore.as_view(), name="explore"),
]

cyberexperiment/lab/urls.py
from django.urls import path

from .views import (
    AllCreator,
    Analytic,
    Checkout,
    CourseDetail,
    CreateCourse,
    Explore,
    FeedBack,
    LiveVideo,
    Membership,
    Message,
    MyContent,
    Notification,
    Review,
)

app_name = "lab"
urlpatterns = [
    path("content/", CreateCourse.as_view(), name="create_course"),
    path("my_content/", MyContent.as_view(), name="my_content"),
    path("analytic/", Analytic.as_view(), name="analytic"),
    path("review/", Review.as_view(), name="review"),
    path("message/", Message.as_view(), name="message"),
    path("notification/", Notification.as_view(), name="notification"),
    path("feedback/", FeedBack.as_view(), name="feedback"),
    path("experiment/", CourseDetail.as_view(), name="course_detail"),
    path("watch_experiment/", LiveVideo.as_view(), name="watch_experiment"),
    path("creators/", AllCreator.as_view(), name="creators"),
    path("explore_experiments/", Explore.as_view(), name="explore"),
    path("membership/", Membership.as_view(), name="membership"),
    path("checkout/", Checkout.as_view(), name="checkout"),
]

cyberexperiment/users/urls.py
from django.urls import path

from cyberexperiment.users.views import (
    CreatorDashboard,
    Profile,
    Setting,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("profile/", Profile.as_view(), name="profile"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
    path("creator_dashboard/", CreatorDashboard.as_view(), name="creator_dashboard"),
    path("setting/", Setting.as_view(), name="setting"),
]

cyberexperiment/core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import redirect


class TimeStamp(models.Model):
    """timestamp to capture all the time of event in the database"""

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# general model
class General(models.Model):
    """General model enable other models similar fields to be inherited. it is use to enforce dry principle"""

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True)
    detail = models.TextField(blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Blog(TimeStamp, General):
    excerpt = models.TextField(blank=True)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return redirect("core:detail", kwargs={"slug": self.slug})


class Event(TimeStamp, General):
    excerpt = models.TextField(blank=True)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return redirect("core:detail", kwargs={"slug": self.slug})


# class Message(TimeStamp):
#     sender = models.ManyToManyField(settings.)


class Notification(TimeStamp):
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(blank=True)

    def __str__(self):
        self.receiver.username

cyberexperiment/lab/models.py
from django.conf import settings
from django.db import models

from cyberexperiment.users.models import UserMembership


class TimeStamp(models.Model):
    """timestamp to capture all the time of event in the database"""

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# general model
class General(models.Model):
    """General model enable other models similar fields to be inherited. it is use to enforce dry principle"""

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True)
    detail = models.TextField(blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Category(TimeStamp, General):
    def __str__(self):
        return self.title


# class LabSubscription(TimeStamp):
#     active = models.BooleanField(default=False)
#     user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
#     payment_subcription_id = models.CharField(max_length=50)

#     def __str__(self):
#         return self.user_membership.user.username


class Lab(TimeStamp, General):
    """Before a user create a content, he must host a lab first"""

    users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="lab_user")

    def __init__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Lab"


class LabCourse(TimeStamp, General):
    """This enable creators create courses and experiment others can follow"""

    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Lab Content"


class Lesson(TimeStamp, General):
    """lessons will be linked to a lab course that will enable the users to create multiple lessons"""

    free = models.BooleanField(default=False)
    video = models.URLField(blank=True)
    video_thumbnail = models.ImageField(blank=True, upload_to="lesson/")
    attachments = models.FileField(blank=True, upload_to="lesson/")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Lesson"


class MultiImage(TimeStamp):
    """This will enable creating multiple images on the model"""


class Content(TimeStamp, General):
    LEVEL = {
        ("beginner", "beginner"),
        ("intermediate", "intermediate"),
        ("professionals", "professionals"),
    }
    LANGUAGE = {("en", "English"), ("fr", "French")}
    short_description = models.TextField(blank=True)
    content_description = models.TextField(blank=True)
    what_student_will_learned = models.TextField(
        blank=True, help_text="What will students learn in your course?"
    )
    requirements = models.TextField(blank=True, help_text="requirements")
    content_level = models.CharField(choices=LEVEL, max_length=255, default="beginner")
    audio_language = models.CharField(choices=LANGUAGE, max_length=200, default="en")
    caption_language = models.CharField(choices=LANGUAGE, max_length=200, default="en")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Topic(TimeStamp, General):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="topic/")
    membership_type = models.ForeignKey(UserMembership, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

cyberexperiment/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

cyberexperiment/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "core/index.html"


class AboutView(TemplateView):
    template_name = "core/about.html"


class BlogView(TemplateView):
    template_name = "core/blog.html"


class ContactView(TemplateView):
    template_name = "core/contact.html"


class BlogDetailView(TemplateView):
    template_name = "core/blog-detail.html"


class EventView(TemplateView):
    template_name = "core/events.html"


class FollowerView(TemplateView):
    template_name = "core/follower.html"


class InstructorView(TemplateView):
    template_name = "core/instructor.html"


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "circus/index.html"


class Explore(TemplateView):
    template_name = "core/explore.html"

cyberexperiment/lab/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


class CreateCourse(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/create_new_course.html"


class MyContent(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/my_contents.html"


class Analytic(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/analytic.html"


class Message(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/messages.html"


class Notification(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/notification.html"


class Review(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/review.html"


class FeedBack(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/feedback.html"


class CourseDetail(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/course_detail_view.html"


class LiveVideo(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/live_output.html"


class AllCreator(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/all_instructor.html"


class Explore(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/explore.html"


class Membership(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/membership.html"


class Checkout(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/checkout_membership.html"

cyberexperiment/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, TemplateView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class Profile(TemplateView):
    template_name = "circus/profile.html"


class CreatorDashboard(TemplateView):
    template_name = "circus/creator_dashboard.html"


class Setting(TemplateView):
    template_name = "circus/setting.html"

cyberexperiment/templates/circus/base_two/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, shrink-to-fit=9" />
    <meta name="description" content="Gambolthemes" />
    <meta name="author" content="Gambolthemes" />
    <title>{% block title %} {% endblock title %}</title>

    <link
      rel="icon"
      type="{% static 'circus/image/png' %}"
      href="{% static 'circus/images/fav.png' %}"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700,500"
      rel="stylesheet"
    />
      <link href="{% static 'circus/css/instructor-dashboard.css' %}" rel="stylesheet" />

 <link href="{% static 'circus/css/datepicker.min.css' %}" rel="stylesheet" />
    <link
      href="{% static 'circus/vendor/unicons-2.0.1/css/unicons.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'circus/css/vertical-responsive-menu.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'circus/css/style.css' %}" rel="stylesheet" />
    <link href="{% static 'circus/css/responsive.css' %}" rel="stylesheet" />
    <link href="{% static 'circus/css/night-mode.css' %}" rel="stylesheet" />

    <link
      href="{% static 'circus/vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'circus/vendor/OwlCarousel/assets/owl.carousel.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'circus/vendor/OwlCarousel/assets/owl.theme.default.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'circus/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'circus/vendor/semantic/semantic.min.css' %}"
    />
  </head>
  <body>
    {% include 'circus/base_two/course_content.html' %}
     {% include 'circus/base_one/header.html' %}
     {% include 'circus/base_two/left_side_bar.html' %} {% block content %}
     {% endblock content %} {% include 'circus/base_two/footer.html' %}
    <script src="{% static 'circus/js/vertical-responsive-menu.min.js' %}"></script>
    <script src="{% static 'circus/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'circus/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'circus/vendor/OwlCarousel/owl.carousel.js' %}"></script>
    <script src="{% static 'circus/vendor/semantic/semantic.min.js' %}"></script>
    <script src="{% static 'circus/js/custom.js' %}"></script>
    <script src="{% static 'circus/js/custom1.js' %}"></script>
    <script src="{% static 'circus/js/night-mode.js' %}"></script>
    <script src="{% static 'circus/js/jquery-steps.min.js' %}"></script>
    <script src="{% static 'circus/vendor/charts/Chart.min.js' %}"></script>
    <script src="{% static 'circus/js/chart.js' %}"></script>
    <script>
      $("#add-course-tab").steps({
        onFinish: function () {
          alert("Wizard Completed");
        },
      });
    </script>
    <script>
      $(function () {
        $(".sortable").sortable();
        $(".sortable").disableSelection();
      });
    </script>
  </body>
</html>

cyberexperiment/templates/circus/base_two/footer.html
{% load static %}
<footer class="footer mt-40">
<div class="container-fluid">
<div class="row">
<div class="col-lg-12">
<div class="item_f1">
<a href="terms_of_use.html">Copyright Policy</a>
<a href="terms_of_use.html">Terms</a>
<a href="terms_of_use.html">Privacy Policy</a>
</div>
</div>
<div class="col-lg-12">
<div class="footer_bottm">
<div class="row">
<div class="col-md-6">
<ul class="fotb_left">
<li>
<a href="index.html">
<div class="footer_logo">
<img src="images/logo1.svg" alt="">
</div>
</a>
</li>
<li>
<p>© 2020 <strong>Cyber Experiment</strong>. All Rights Reserved.</p>
</li>
</ul>
</div>
<div class="col-md-6">
<div class="edu_social_links">
<a href="#"><i class="fab fa-facebook-f"></i></a>
<a href="#"><i class="fab fa-twitter"></i></a>
<a href="#"><i class="fab fa-google-plus-g"></i></a>
<a href="#"><i class="fab fa-linkedin-in"></i></a>
<a href="#"><i class="fab fa-instagram"></i></a>
<a href="#"><i class="fab fa-youtube"></i></a>
<a href="#"><i class="fab fa-pinterest-p"></i></a>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</footer>
</div>

cyberexperiment/templates/circus/base_two/left_side_bar.html
{% load static %}
<nav class="vertical_nav">
  <div class="left_section menu_left" id="js-menu">
    <div class="left_section">
      <ul>
        <li class="menu--item">
          <a
            href="{% url 'users:creator_dashboard' %}"
            class="menu--link"
            title="Dashboard"
          >
            <i class="uil uil-apps menu--icon"></i>
            <span class="menu--label">Dashboard</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="{% url 'lab:my_content' %}"
            class="menu--link"
            title="Courses"
          >
            <i class="uil uil-book-alt menu--icon"></i>
            <span class="menu--label">Courses</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="{% url 'lab:analytic' %}"
            class="menu--link"
            title="Analyics"
          >
            <i class="uil uil-analysis menu--icon"></i>
            <span class="menu--label">Analyics</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="{% url 'lab:create_course' %}"
            class="menu--link active"
            title="Start An Experiment"
          >
            <i class="uil uil-plus-circle menu--icon"></i>
            <span class="menu--label">Create Content</span>
          </a>
        </li>
        <li class="menu--item">
          <a href="{% url 'lab:message' %}" class="menu--link" title="Messages">
            <i class="uil uil-comments menu--icon"></i>
            <span class="menu--label">Messages</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="{% url 'lab:notification' %}"
            class="menu--link"
            title="Notifications"
          >
            <i class="uil uil-bell menu--icon"></i>
            <span class="menu--label">Notifications</span>
          </a>
        </li>
        <li class="menu--item">
          <a href="{% url 'lab:review' %}" class="menu--link" title="Reviews">
            <i class="uil uil-star menu--icon"></i>
            <span class="menu--label">Reviews</span>
          </a>
        </li>
        <li class="menu--item">
          <a href="instructor_earning.html" class="menu--link" title="Earning">
            <i class="uil uil-dollar-sign menu--icon"></i>
            <span class="menu--label">Earning</span>
          </a>
        </li>
        <li class="menu--item">
          <a href="instructor_payout.html" class="menu--link" title="Payout">
            <i class="uil uil-wallet menu--icon"></i>
            <span class="menu--label">Payout</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="instructor_statements.html"
            class="menu--link"
            title="Statements"
          >
            <i class="uil uil-file-alt menu--icon"></i>
            <span class="menu--label">Statements</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="instructor_verification.html"
            class="menu--link"
            title="Verification"
          >
            <i class="uil uil-check-circle menu--icon"></i>
            <span class="menu--label">Verification</span>
          </a>
        </li>
      </ul>
    </div>
    <div class="left_section pt-2">
      <ul>
        <li class="menu--item">
          <a
            href="{% url 'users:setting' %}"
            class="menu--link"
            title="Setting"
          >
            <i class="uil uil-cog menu--icon"></i>
            <span class="menu--label">Setting</span>
          </a>
        </li>
        <li class="menu--item">
          <a
            href="{% url 'lab:feedback' %}"
            class="menu--link"
            title="Send Feedback"
          >
            <i class="uil uil-comment-alt-exclamation menu--icon"></i>
            <span class="menu--label">Send Feedback</span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>