config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("cyberexperiment.core.urls", namespace="core")),
    path("lab/", include("cyberexperiment.lab.urls", namespace="lab")),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("cyberexperiment.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

cyberexperiment/core/urls.py
from django.urls import path

from .views import (
    AboutView,
    BlogDetailView,
    BlogView,
    ContactView,
    Dashboard,
    EventView,
    Explore,
    FollowerView,
    HomePageView,
    InstructorView,
)

app_name = "core"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("blog/", BlogView.as_view(), name="blog"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("blog-detail", BlogDetailView.as_view(), name="blog-details"),
    path("event/", EventView.as_view(), name="event"),
    path("follower/", FollowerView.as_view(), name="follower"),
    path("instructor/", InstructorView.as_view(), name="instructor"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("explore/", Explore.as_view(), name="explore"),
]

cyberexperiment/lab/urls.py
from django.urls import path

from .views import (
    AllCreator,
    Analytic,
    Checkout,
    CourseDetail,
    CreateCourse,
    Explore,
    FeedBack,
    LiveVideo,
    Membership,
    Message,
    MyContent,
    Notification,
    Review,
)

app_name = "lab"
urlpatterns = [
    path("content/", CreateCourse.as_view(), name="create_course"),
    path("my_content/", MyContent.as_view(), name="my_content"),
    path("analytic/", Analytic.as_view(), name="analytic"),
    path("review/", Review.as_view(), name="review"),
    path("message/", Message.as_view(), name="message"),
    path("notification/", Notification.as_view(), name="notification"),
    path("feedback/", FeedBack.as_view(), name="feedback"),
    path("experiment/", CourseDetail.as_view(), name="course_detail"),
    path("watch_experiment/", LiveVideo.as_view(), name="watch_experiment"),
    path("creators/", AllCreator.as_view(), name="creators"),
    path("explore_experiments/", Explore.as_view(), name="explore"),
    path("membership/", Membership.as_view(), name="membership"),
    path("checkout/", Checkout.as_view(), name="checkout"),
]

cyberexperiment/users/urls.py
from django.urls import path

from cyberexperiment.users.views import (
    CreatorDashboard,
    Profile,
    Setting,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("profile/", Profile.as_view(), name="profile"),
    # path("<str:username>/", view=user_detail_view, name="detail"),
    path("creator_dashboard/", CreatorDashboard.as_view(), name="creator_dashboard"),
    path("setting/", Setting.as_view(), name="setting"),
]

cyberexperiment/core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import redirect


class TimeStamp(models.Model):
    """timestamp to capture all the time of event in the database"""

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# general model
class General(models.Model):
    """General model enable other models similar fields to be inherited. it is use to enforce dry principle"""

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True)
    detail = models.TextField(blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Blog(TimeStamp, General):
    excerpt = models.TextField(blank=True)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return redirect("core:detail", kwargs={"slug": self.slug})


class Event(TimeStamp, General):
    excerpt = models.TextField(blank=True)
    view_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self, *args, **kwargs):
        return redirect("core:detail", kwargs={"slug": self.slug})


# class Message(TimeStamp):
#     sender = models.ManyToManyField(settings.)


class Notification(TimeStamp):
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField(blank=True)

    def __str__(self):
        self.receiver.username

cyberexperiment/lab/models.py
from django.conf import settings
from django.db import models

from cyberexperiment.users.models import UserMembership


class TimeStamp(models.Model):
    """timestamp to capture all the time of event in the database"""

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# general model
class General(models.Model):
    """General model enable other models similar fields to be inherited. it is use to enforce dry principle"""

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True)
    detail = models.TextField(blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        abstract = True


class Category(TimeStamp, General):
    def __str__(self):
        return self.title


# class LabSubscription(TimeStamp):
#     active = models.BooleanField(default=False)
#     user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
#     payment_subcription_id = models.CharField(max_length=50)

#     def __str__(self):
#         return self.user_membership.user.username


class Lab(TimeStamp, General):
    """Before a user create a content, he must host a lab first"""

    users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="lab_user")

    def __init__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Lab"


class LabCourse(TimeStamp, General):
    """This enable creators create courses and experiment others can follow"""

    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Lab Content"


class Lesson(TimeStamp, General):
    """lessons will be linked to a lab course that will enable the users to create multiple lessons"""

    free = models.BooleanField(default=False)
    video = models.URLField(blank=True)
    video_thumbnail = models.ImageField(blank=True, upload_to="lesson/")
    attachments = models.FileField(blank=True, upload_to="lesson/")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Lesson"


class MultiImage(TimeStamp):
    """This will enable creating multiple images on the model"""


class Content(TimeStamp, General):
    LEVEL = {
        ("beginner", "beginner"),
        ("intermediate", "intermediate"),
        ("professionals", "professionals"),
    }
    LANGUAGE = {("en", "English"), ("fr", "French")}
    short_description = models.TextField(blank=True)
    content_description = models.TextField(blank=True)
    what_student_will_learned = models.TextField(
        blank=True, help_text="What will students learn in your course?"
    )
    requirements = models.TextField(blank=True, help_text="requirements")
    content_level = models.CharField(choices=LEVEL, max_length=255, default="beginner")
    audio_language = models.CharField(choices=LANGUAGE, max_length=200, default="en")
    caption_language = models.CharField(choices=LANGUAGE, max_length=200, default="en")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Topic(TimeStamp, General):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to="topic/")
    membership_type = models.ForeignKey(UserMembership, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

cyberexperiment/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

cyberexperiment/core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "core/index.html"


class AboutView(TemplateView):
    template_name = "core/about.html"


class BlogView(TemplateView):
    template_name = "core/blog.html"


class ContactView(TemplateView):
    template_name = "core/contact.html"


class BlogDetailView(TemplateView):
    template_name = "core/blog-detail.html"


class EventView(TemplateView):
    template_name = "core/events.html"


class FollowerView(TemplateView):
    template_name = "core/follower.html"


class InstructorView(TemplateView):
    template_name = "core/instructor.html"


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = "circus/index.html"


class Explore(TemplateView):
    template_name = "core/explore.html"

cyberexperiment/lab/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic


class CreateCourse(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/create_new_course.html"


class MyContent(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/my_contents.html"


class Analytic(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/analytic.html"


class Message(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/messages.html"


class Notification(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/notification.html"


class Review(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/review.html"


class FeedBack(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/feedback.html"


class CourseDetail(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/course_detail_view.html"


class LiveVideo(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/live_output.html"


class AllCreator(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/all_instructor.html"


class Explore(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/explore.html"


class Membership(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/membership.html"


class Checkout(LoginRequiredMixin, generic.TemplateView):
    template_name = "circus/checkout_membership.html"

cyberexperiment/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, TemplateView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class Profile(TemplateView):
    template_name = "circus/profile.html"


class CreatorDashboard(TemplateView):
    template_name = "circus/creator_dashboard.html"


class Setting(TemplateView):
    template_name = "circus/setting.html"

cyberexperiment/templates/core/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
  <head>
    <!-- meta tag -->
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock%}</title>
    <meta name="description" content="" />
    <!-- responsive tag -->
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- favicon -->
    <link rel="apple-touch-icon" href="apple-touch-icon.html" />
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'core/assets/images/fav-orange.png' %}"
    />
    <!-- Bootstrap v4.4.1 css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/bootstrap.min.css' %}"
    />
    <!-- font-awesome css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/font-awesome.min.css' %}"
    />
    <!-- animate css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/animate.css' %}"
    />
    <!-- owl.carousel css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/owl.carousel.css' %}"
    />
    <!-- slick css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/slick.css' %}"
    />
    <!-- off canvas css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/off-canvas.css' %}"
    />
    <!-- linea-font css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/fonts/linea-fonts.css' %}"
    />
    <!-- flaticon css  -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/fonts/flaticon.css' %}"
    />
    <!-- magnific popup css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/magnific-popup.css' %}"
    />
    <!-- Main Menu css -->
    <link
      rel="stylesheet"
      href="{% static 'core/assets/css/rsmenu-main.css' %}"
    />
    <!-- spacing css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/rs-spacing.css' %}"
    />
    <!-- style css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/style.css' %}"
    />
    <!-- This stylesheet dynamically changed from style.less -->
    <!-- responsive css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'core/assets/css/responsive.css' %}"
    />
    <style>
      .picture_circle{
        display:flex;
        border-radius:78% 45% 68% 23% / 77% 88% 26% 41%;
        height:500px;
        }
    </style>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="defult-home">
    <!--Preloader area start here-->
    <div id="loader" class="loader orange-color">
      <div class="loader-container">
        <div class="loader-icon">
          <img src="{% static 'core/assets/images/pre-logo1.png' %}" alt="" />
        </div>
      </div>
    </div>
    <!--Preloader area End here-->
    <!-- Main content Start -->
    <div class="main-content">
      {% include "./header.html" %} {% block content %} {% endblock content %}
    </div>
    <!-- Main content End -->

    {% include "./footer.html" %}
  </body>
</html>

cyberexperiment/templates/core/base/footer.html
{% load static %}
  <!-- Footer Start -->
        <footer id="rs-footer" class="rs-footer home9-style main-home">
            <div class="footer-top">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-3 col-md-12 col-sm-12 footer-widget md-mb-50">
                            <div class="footer-logo mb-30">
                                <a href="index.html"><img src="{% static 'core/main.png' %}" alt=""></a>
                            </div>
                              <div class="textwidget pr-60 md-pr-15"><p class="white-color">We denounce with righteous indi gnation and dislike men who are so beguiled and demoralized by the charms of pleasure of your moment, so blinded by desire those who fail weakness.</p>
                              </div>
                              <ul class="footer_social">
                                  <li>
                                      <a href="#" target="_blank"><span><i class="fa fa-facebook"></i></span></a>
                                  </li>
                                  <li>
                                      <a href="# " target="_blank"><span><i class="fa fa-twitter"></i></span></a>
                                  </li>

                                  <li>
                                      <a href="# " target="_blank"><span><i class="fa fa-pinterest-p"></i></span></a>
                                  </li>
                                  <li>
                                      <a href="# " target="_blank"><span><i class="fa fa-google-plus-square"></i></span></a>
                                  </li>
                                  <li>
                                      <a href="# " target="_blank"><span><i class="fa fa-instagram"></i></span></a>
                                  </li>

                              </ul>
                        </div>
                        <div class="col-lg-3 col-md-12 col-sm-12 footer-widget md-mb-50">
                            <h3 class="widget-title">Address</h3>
                            <ul class="address-widget">
                                <li>
                                    <i class="flaticon-location"></i>
                                    <div class="desc">374 William S Canning Blvd, River MA 2721, USA</div>
                                </li>
                                <li>
                                    <i class="flaticon-call"></i>
                                    <div class="desc">
                                       <a href="tel:(+880)155-69569">(+880)155-69569</a>
                                    </div>
                                </li>
                                <li>
                                    <i class="flaticon-email"></i>
                                    <div class="desc">
                                        <a href="mailto:support@rstheme.com">support@cyberexperiment.com</a>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-3 col-md-12 col-sm-12 pl-50 md-pl-15 footer-widget md-mb-50">
                            <h3 class="widget-title">Courses</h3>
                            <ul class="site-map">
                                <li><a href="#">Lab</a></li>
                                <li><a href="#">Course</a></li>
                                <li><a href="#">Follow</a></li>
                                <li><a href="#">Profile</a></li>
                                <li><a href="#">Login/Register</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3 col-md-12 col-sm-12 footer-widget">
                            <h3 class="widget-title">Recent Posts</h3>
                            <div class="recent-post mb-20">
                                <div class="post-img">
                                    <img src="{% static 'core/assets/images/footer/1.jpg' %}" alt="">
                                </div>
                                <div class="post-item">
                                    <div class="post-desc">
                                        <a href="#">University while the lovely valley team work</a>
                                    </div>
                                    <span class="post-date">
                                        <i class="fa fa-calendar"></i>
                                        September 20, 2020
                                    </span>
                                </div>
                            </div>
                            <div class="recent-post mb-20 md-pb-0">
                                <div class="post-img">
                                    <img src="{% static 'core/assets/images/footer/2.jpg' %}" alt="">
                                </div>
                                <div class="post-item">
                                    <div class="post-desc">
                                        <a href="#">High school program starting soon 2021</a>
                                    </div>
                                    <span class="post-date">
                                       <i class="fa fa-calendar-check-o"></i>
                                        September 14, 2020
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-bottom">
                <div class="container">
                    <div class="row y-middle">
                        <div class="col-lg-6 md-mb-20">
                            <div class="copyright">
                                <p>&copy; 2020 All Rights Reserved. Developed By <a href="http://cnctechnolgies.io">CNC Technologies</a></p>
                            </div>
                        </div>
                        <div class="col-lg-6 text-right md-text-left">
                            <ul class="copy-right-menu">
                                <li><a href="#">Event</a></li>
                                <li><a href="#">Blog</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Footer End -->

        <!-- start scrollUp  -->
        <div id="scrollUp" class="orange-color">
            <i class="fa fa-angle-up"></i>
        </div>
        <!-- End scrollUp  -->

        <!-- Search Modal Start -->
        <div aria-hidden="true" class="modal fade search-modal" role="dialog" tabindex="-1">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span class="flaticon-cross"></span>
            </button>
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="search-block clearfix">
                        <form>
                            <div class="form-group">
                                <input class="form-control" placeholder="Search Here..." type="text">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Search Modal End -->

        <!-- modernizr js -->
        <script src="{% static 'core/assets/js/modernizr-2.8.3.min.js' %}"></script>
        <!-- jquery latest version -->
        <script src="{% static 'core/assets/js/jquery.min.js' %}"></script>
        <!-- Bootstrap v4.4.1 js -->
        <script src="{% static 'core/assets/js/bootstrap.min.js' %}"></script>
        <!-- Menu js -->
        <script src="{% static 'core/assets/js/rsmenu-main.js' %}"></script>
        <!-- op nav js -->
        <script src="{% static 'core/assets/js/jquery.nav.js' %}"></script>
        <!-- owl.carousel js -->
        <script src="{% static 'core/assets/js/owl.carousel.min.js' %}"></script>
        <!-- Slick js -->
        <script src="{% static 'core/assets/js/slick.min.js' %}"></script>
        <!-- isotope.pkgd.min js -->
        <script src="{% static 'core/assets/js/isotope.pkgd.min.js' %}"></script>
        <!-- imagesloaded.pkgd.min js -->
        <script src="{% static 'core/assets/js/imagesloaded.pkgd.min.js' %}"></script>
        <!-- wow js -->
        <script src="{% static 'core/assets/js/wow.min.js' %}"></script>
        <!-- Skill bar js -->
        <script src="{% static 'core/assets/js/skill.bars.jquery.js' %}"></script>
        <script src="{% static 'core/assets/js/jquery.counterup.min.js' %}"></script>
         <!-- counter top js -->
        <script src="{% static 'core/assets/js/waypoints.min.js' %}"></script>
        <!-- video js -->
        <script src="{% static 'core/assets/js/jquery.mb.YTPlayer.min.js' %}"></script>
        <!-- magnific popup js -->
        <script src="{% static 'core/assets/js/jquery.magnific-popup.min.js' %}"></script>
        <!-- plugins js -->
        <script src="{% static 'core/assets/js/plugins.js' %}"></script>
        <!-- contact form js -->
        <script src="{% static 'core/assets/js/contact.form.js' %}"></script>
        <!-- main js -->
        <script src="{% static 'core/assets/js/main.js' %}"></script>
    </body>
</html>

cyberexperiment/templates/core/base/header.html
{% load static %}
<!--Full width header Start-->
<div class="full-width-header home8-style4 main-home">
  <!--Header Start-->
  <header id="rs-header" class="rs-header">
    <!-- Menu Start -->
    <div class="menu-area menu-sticky">
      <div class="container">
        <div class="row y-middle">
          <div class="col-lg-2">
            <div class="logo-cat-wrap">
              <div class="logo-part">
                <a href="{% url 'core:home' %}">
                  <img
                    class="normal-logo"
                    src="{% static 'core/trans.png' %}"
                    alt=""
                  />
                  <img
                    class="sticky-logo"
                    src="{% static 'core/main.png' %}"
                    alt=""
                  />
                </a>
              </div>
            </div>
          </div>
          <div class="col-lg-8 text-right">
            <div class="rs-menu-area">
              <div class="main-menu">
                <div class="mobile-menu">
                  <a class="rs-menu-toggle">
                    <i class="fa fa-bars"></i>
                  </a>
                </div>
                <nav class="rs-menu">
                  <ul class="nav-menu">
                    <li
                      class="
                        rs-mega-menu
                        mega-rs
                        menu-item
                        current-menu-item
                      "
                    >
                      <a href="{% url 'core:instructor' %}">Researcher</a>
                      <!-- //.mega-menu -->
                    </li>
                    <li class="menu-item">
                      <a href="{% url 'core:follower' %}">Student</a>
                    </li>

                    <li class="menu-item">
                      <a href="{% url 'core:explore' %}">Explore</a>
                    </li>
                    <li class="menu-item">
                      <a href="{% url 'core:about' %}">About</a>
                    </li>

                    <li class="menu-item">
                      <a href="{% url 'core:contact' %}">Contact</a>
                    </li>
                    <li class="menu-item">
                      {% if user.is_authenticated %}

                      <a href="{% url 'core:dashboard' %}">Dashboard</a>
                      {% else %}
                      <a href="{% url 'account_login' %}">Login</a>
                      {% endif %}
                    </li>
                  </ul>
                  <!-- //.nav-menu -->
                </nav>
              </div>
              <!-- //.main-menu -->
            </div>
          </div>
          <div class="col-lg-2 text-right">

          </div>
        </div>
      </div>
    </div>
    <!-- Menu End -->

  </header>
  <!--Header End-->
</div>
<!--Full width header End-->